title: "Lvl 0 SOC Analyst Ramblings"
remote_theme: pages-themes/hacker@v0.2.0
description: "Project Work, Malware Analysis, Threat Hunting/Intel, Pentesting, CTFs, Privacy content and Scripts you'll never use"
author:
  name: "Lvl 0 SOC"
locale: "en-US"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false


plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.css"